#!/bin/bash

_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $UPSTREAM_REPO == "dev-sonic" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2Rldi1zb25pYy91NjYwcGJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO == "dev-sonic" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL2Rldi1zb25pYy91NjYwcGJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $UPSTREAM_REPO =~ $regex ]]
    then
        if [[ $UPSTREAM_REPO_BRANCH ]]
        then
            echo "${UPSTREAM_REPO}/archive/${UPSTREAM_REPO_BRANCH}.zip"
        else
            echo "${UPSTREAM_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL2Rldi1zb25pYy91NjYwcGJvdC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_setting_bot () {
    local zippath
    zippath="sonicBot.zip"
    echo "  يتم تحميل ملفات سونيك ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  فك بيانات السورس ..."
    sonicPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "✓"
    echo "  يتم التفريغ.."
    rm -rf "$zippath"
    sleep 5
    cd $sonicPATH
    echo "    بدء بوت سونيك    "
    echo "
    "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m userbot
}

_setting_bot